overrides:
  -
    files: './**/*.js'
    env:
      cypress/globals: true
      jest/globals: false
    rules:
      jest/expect-expect: 0
      '@typescript-eslint/no-unsafe-member-access': 0
      '@typescript-eslint/no-unsafe-call': 0
